#!/usr/bin/env python3
"""
HR HUD Activation Server
========================
Two jobs:
  1. Checks a submitted key against an ALLOWLIST of keys you actually
     generated (tools/generate_keys.py) — so only keys you chose to hand
     out will ever work, no matter what pattern someone reverse-engineers.
  2. Tracks which machine ID has "claimed" each allowlisted key, so the
     same key can't be used on two different computers simultaneously.

The allowlist stores SHA-256 hashes of keys, not the plaintext keys
themselves — so if valid_keys.json ever leaks, it doesn't hand out working
keys, only unusable hashes.

Deploy anywhere Python runs: Fly.io, Railway, Render, or even a $5 VPS.

Setup:
    pip install flask
    python3 activation_server.py

Required environment variables (set in your host's config panel):
    HRHUD_SECRET    — any random string used to protect the admin endpoints
    PORT            — port to listen on (default 8080)
    MAX_PER_KEY     — how many machines can share one key (default 1)
    KEYS_DB_PATH    — path to the allowlist file (default valid_keys.json)
    DB_PATH         — path to the activations file (default activations.json)

Endpoints:
    POST /activate        {"key": "XXXX-XXXX-XXXX-XXXX", "machineId": "..."}
    POST /deactivate      {"key": "...", "machineId": "...", "adminSecret": "..."}
    GET  /status/<key>    {"key": "...", "activations": [...]}  (requires ?secret=)
    POST /admin/add-key   {"key": "...", "adminSecret": "..."}  — add a key to the allowlist
    POST /admin/revoke-key {"key": "...", "adminSecret": "..."} — remove a key from the allowlist
"""

import hashlib, json, os
from pathlib import Path
from flask import Flask, request, jsonify, abort

app = Flask(__name__)

SECRET      = os.environ.get("HRHUD_SECRET",  "change-this-admin-secret")
MAX_PER_KEY = int(os.environ.get("MAX_PER_KEY", "1"))
PORT        = int(os.environ.get("PORT",        "8080"))
DB_PATH     = Path(os.environ.get("DB_PATH",   "activations.json"))
KEYS_DB_PATH = Path(os.environ.get("KEYS_DB_PATH", "valid_keys.json"))

ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


# ── helpers ───────────────────────────────────────────────────────────────────

def load_db() -> dict:
    if DB_PATH.exists():
        try:
            return json.loads(DB_PATH.read_text())
        except Exception:
            pass
    return {}

def save_db(data: dict):
    DB_PATH.write_text(json.dumps(data, indent=2))

def load_allowlist() -> set:
    """Returns the set of allowlisted key hashes."""
    if KEYS_DB_PATH.exists():
        try:
            return set(json.loads(KEYS_DB_PATH.read_text()))
        except Exception:
            pass
    return set()

def save_allowlist(hashes: set):
    KEYS_DB_PATH.write_text(json.dumps(sorted(hashes), indent=2))

def key_hash(key: str) -> str:
    return hashlib.sha256(key.encode()).hexdigest()

def is_well_formed(key: str) -> bool:
    """Shape check only — does NOT mean the key is real. See is_allowlisted."""
    key = key.strip().upper().replace(" ", "")
    groups = key.split("-")
    if len(groups) != 4 or any(len(g) != 4 for g in groups):
        return False
    if any(c not in ALPHABET for g in groups for c in g):
        return False
    return True

def is_allowlisted(key: str) -> bool:
    """The actual source of truth: was this key ever generated by you?"""
    key = key.strip().upper().replace(" ", "")
    return key_hash(key) in load_allowlist()

def require_json(*fields):
    body = request.get_json(silent=True) or {}
    missing = [f for f in fields if not body.get(f)]
    if missing:
        abort(400, description=f"Missing fields: {', '.join(missing)}")
    return body


# ── routes ────────────────────────────────────────────────────────────────────

@app.post("/verify")
def verify():
    """Called by the app on every launch to confirm a previously-activated
    key is still good. Unlike /activate, this does NOT claim a new machine
    slot — it just checks (a) the key is still on the allowlist (hasn't
    been revoked) and (b) this specific machine is still the one it's
    bound to. No admin secret required since every regular user calls this."""
    body    = require_json("key", "machineId")
    key     = body["key"].strip().upper().replace(" ", "")
    machine = body["machineId"].strip()[:64]

    if not is_allowlisted(key):
        return jsonify(ok=False, valid=False, reason="revoked")

    db = load_db()
    bound_machines = db.get(key, [])
    if machine not in bound_machines:
        return jsonify(ok=False, valid=False, reason="not_bound_to_this_machine")

    return jsonify(ok=True, valid=True)


@app.post("/activate")
def activate():
    body      = require_json("key", "machineId")
    key       = body["key"].strip().upper().replace(" ", "")
    machine   = body["machineId"].strip()[:64]   # cap length

    if not is_well_formed(key):
        return jsonify(ok=False, error="Invalid license key."), 400

    if not is_allowlisted(key):
        return jsonify(ok=False, error="This key doesn't exist. Double-check it and try again."), 403

    db = load_db()
    activations: list = db.get(key, [])

    # already activated on THIS machine — always OK
    if machine in activations:
        return jsonify(ok=True)

    if len(activations) >= MAX_PER_KEY:
        return jsonify(
            ok=False,
            error=(
                f"This key is already active on another machine. "
                f"Each key allows {MAX_PER_KEY} activation(s). "
                "Contact support if you need to transfer it."
            )
        ), 403

    activations.append(machine)
    db[key] = activations
    save_db(db)
    return jsonify(ok=True)


@app.post("/deactivate")
def deactivate():
    """Admin endpoint to free a key slot (e.g. customer lost their machine)."""
    body   = require_json("key", "machineId", "adminSecret")
    if body["adminSecret"] != SECRET:
        abort(403, description="Bad admin secret.")

    key     = body["key"].strip().upper()
    machine = body["machineId"].strip()
    db      = load_db()
    acts    = db.get(key, [])
    if machine in acts:
        acts.remove(machine)
        db[key] = acts
        save_db(db)
    return jsonify(ok=True, remaining=len(acts))


@app.get("/status/<key>")
def status(key: str):
    if request.args.get("secret") != SECRET:
        abort(403)
    db = load_db()
    key = key.strip().upper()
    return jsonify(key=key, activations=db.get(key, []), valid=is_allowlisted(key))


@app.post("/admin/add-key")
def admin_add_key():
    """Adds a key to the allowlist. Called by generate_keys.py --push, or
    manually when you mint a key for a specific customer."""
    body = require_json("key", "adminSecret")
    if body["adminSecret"] != SECRET:
        abort(403, description="Bad admin secret.")

    key = body["key"].strip().upper().replace(" ", "")
    if not is_well_formed(key):
        return jsonify(ok=False, error="Not a well-formed key."), 400

    allowlist = load_allowlist()
    allowlist.add(key_hash(key))
    save_allowlist(allowlist)
    return jsonify(ok=True)


@app.post("/admin/revoke-key")
def admin_revoke_key():
    """Removes a key from the allowlist entirely (e.g. refund, chargeback,
    leaked key). Existing activations for it are also cleared."""
    body = require_json("key", "adminSecret")
    if body["adminSecret"] != SECRET:
        abort(403, description="Bad admin secret.")

    key = body["key"].strip().upper().replace(" ", "")
    allowlist = load_allowlist()
    allowlist.discard(key_hash(key))
    save_allowlist(allowlist)

    db = load_db()
    db.pop(key, None)
    save_db(db)
    return jsonify(ok=True)


@app.post("/admin/reset-all")
def admin_reset_all():
    """⚠️ Wipes every key and every activation. Any key already handed out
    to a customer stops working immediately. Used by tools/reset_keys.py."""
    body = require_json("adminSecret")
    if body["adminSecret"] != SECRET:
        abort(403, description="Bad admin secret.")

    save_allowlist(set())
    save_db({})
    return jsonify(ok=True)


@app.get("/admin/list-activations")
def admin_list_activations():
    """Lists every key that has at least one activation, and which machines
    hold it. Does NOT show keys that were generated but never activated —
    the server never stores plaintext keys it hasn't seen used, only hashes.
    For your full list of issued keys, check tools/issued_keys.log, which
    generate_keys.py writes to locally every time you mint a key."""
    if request.args.get("secret") != SECRET:
        abort(403)
    db = load_db()
    return jsonify(count=len(db), activations=db)


@app.get("/health")
def health():
    return jsonify(ok=True, product="HR HUD activation server")


# ── entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"HR HUD activation server — port {PORT}, max {MAX_PER_KEY} activation(s) per key")
    print(f"DB: {DB_PATH.resolve()}")
    app.run(host="0.0.0.0", port=PORT)
